version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
        restart: always
        depends_on:
            - frontend
            - backend

    redis:
        image: redis:latest
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]
        restart: always


    frontend:
        build: ./frontend
        command: "npm run dev"
        volumes: 
            - ./frontend/app/:/usr/src/app/
        restart: always
        depends_on: 
            - backend

    backend:
        build: ./backend
        command: bash -c "npm install && npm run dev"
        volumes:
            - ./backend/app/:/usr/src/
            - ./backend/.aws/:/root/.aws/
        restart: always
        depends_on:
            - redis
        environment: 
            - REDIS_URL=redis://cache
