version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - frontend
            - backend

    redis:
        image: redis:latest
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]

    frontend:
        build: ./frontend
        command: "npm run dev"
        volumes: 
            - ./frontend/app/:/usr/src/app/
        depends_on: 
            - backend

    backend:
        build: ./backend
        command: "npm run dev"
        volumes:
            - ./backend/controllers/:/usr/src/controllers/
            - ./backend/middlewares/:/usr/src/middlewares/
            - ./backend/routes/:/usr/src/routes/
            - ./backend/services/:/usr/src/services/
            - ./backend/utils/:/usr/src/utils/
            - ./backend/config/:/usr/src/config/
            - ./backend/app.js:/usr/src/app.js
        environment: 
            - REDIS_URL=redis://cache
