version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - frontend
            - backend

    redis:
        image: redis:latest
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]

    frontend:
        image: whereismyrum/portfolio-frontend:latest
        command: "npm run start"
        depends_on: 
            - backend

    backend:
        image: whereismyrum/portfolio-backend:latest
        command: "npm run start"
        volumes:
            - ./backend/.aws/:/root/.aws/
        depends_on:
            - redis
        environment: 
            - REDIS_URL=redis://cache
