version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 6895:443
        volumes:
            - ./nginx/conf.d/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
            - ./nginx/clear-cache.sh:/usr/src/scripts/clear-cache.sh
        restart: always
        depends_on:
            - frontend
            - backend

    redis:
        image: redis:latest
        container_name: cache
        command: ["redis-server", "--appendonly", "yes"]
        restart: always


    frontend:
        image: whereismyrum/portfolio-frontend:latest
        command: "npm run start"
        restart: always
        depends_on: 
            - backend

    backend:
        image: whereismyrum/portfolio-backend:latest
        command: "npm run start"
        volumes:
            - ./backend/.aws/:/root/.aws/
        restart: always
        depends_on:
            - redis
        environment: 
            - REDIS_URL=redis://cache
