version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a1:a0:4a:f3:82:af:46:2e:bc:de:3d:a8:a1:54:2f:8b"
      - run:
          name: Deploy app to AWS EC2 via Docker
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-59-234-24.eu-central-1.compute.amazonaws.com "cd production && git pull && /bin/bash deploy_app.sh"

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master